version: 2
updates:
  # Update npm dependencies in the frontend directory
  - package-ecosystem: "npm"
    directory: /apps/frontend
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  # Update npm dependencies in the admin directory
  - package-ecosystem: "npm"
    directory: /apps/admin
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  # Update go dependencies in the backend directory
  - package-ecosystem: "gomod"
    directory: /apps/backend
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  # Update github actions dependencies in the root directory
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
